version: 0.0

hooks:
  BeforeInstall:
    - location: scripts/fetch_from_github.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_lambda_function.sh
      timeout: 300
      runas: root
